/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./app/src/**/*.{js,ts,jsx,tsx}"],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── NX Design System ──
        'nx-void':           'var(--nx-void)',
        'nx-depth':          'var(--nx-depth)',
        'nx-surface':        'var(--nx-surface)',
        'nx-overlay':        'var(--nx-overlay)',
        'nx-border':         'var(--nx-border)',
        'nx-muted':          'var(--nx-muted)',
        'nx-subtle':         'var(--nx-subtle)',
        'nx-dim':            'var(--nx-dim)',
        'nx-text':           'var(--nx-text)',
        'nx-bright':         'var(--nx-bright)',
        'nx-primary':        'var(--nx-primary)',
        'nx-primary-hover':  'var(--nx-primary-hover)',
        'nx-primary-active': 'var(--nx-primary-active)',
        'nx-secondary':      'var(--nx-secondary)',
        'nx-accent':         'var(--nx-accent)',
        'nx-hot':            'var(--nx-hot)',
        'nx-success':        'var(--nx-success)',
        'nx-error':          'var(--nx-error)',
        'nx-warning':        'var(--nx-warning)',
        'nx-info':           'var(--nx-info)',
        // ── Legacy aliases ──
        'surface-base':      'var(--surface-base)',
        'surface-raised':    'var(--surface-raised)',
        'surface-card':      'var(--surface-card)',
        'surface-elevated':  'var(--surface-elevated)',
        'surface-border':    'var(--surface-border)',
        'surface-input':     'var(--surface-input)',
        'bg-primary':        'var(--surface-base)',
        'bg-secondary':      'var(--surface-raised)',
        'bg-tertiary':       'var(--surface-card)',
        'accent-main':       'var(--color-brand)',
        'accent-light':      'var(--color-chat)',
        'text-primary':      'var(--text-hi)',
        'text-secondary':    'var(--text-mid)',
        'text-muted':        'var(--text-lo)',
        'text-hi':           'var(--text-hi)',
        'text-mid':          'var(--text-mid)',
        'text-lo':           'var(--text-lo)',
        'border-subtle':     'var(--surface-border)',
        'color-brand':       'var(--color-brand)',
        'color-notas':       'var(--color-notas)',
        'color-estudo':      'var(--color-estudo)',
        'color-flashcards':  'var(--color-flashcards)',
        'color-gerador':     'var(--color-gerador)',
        'color-chat':        'var(--color-chat)',
        'color-grafo':       'var(--color-grafo)',
        'color-stats':       'var(--color-stats)',
        'color-warning':     'var(--color-warning)',
        'color-success':     'var(--color-success)',
        'color-error':       'var(--color-error)',
        'success':  'var(--color-success)',
        'warning':  'var(--color-warning)',
        'danger':   'var(--color-error)',
        'info':     'var(--color-info)',
        'xp':       'var(--color-gerador)',
      },
      fontSize: {
        'nx-xs':      ['11px', { lineHeight: '1.4' }],
        'nx-sm':      ['12px', { lineHeight: '1.4' }],
        'nx-base':    ['14px', { lineHeight: '1.5' }],
        'nx-md':      ['15px', { lineHeight: '1.5' }],
        'nx-lg':      ['17px', { lineHeight: '1.4' }],
        'nx-xl':      ['20px', { lineHeight: '1.3' }],
        'nx-2xl':     ['24px', { lineHeight: '1.2' }],
        'nx-3xl':     ['30px', { lineHeight: '1.2' }],
        'nx-display': ['42px', { lineHeight: '1.1' }],
        'title-xl': ['1.75rem',   { fontWeight: '600', lineHeight: '1.2' }],
        'title-l':  ['1.375rem',  { fontWeight: '600', lineHeight: '1.3' }],
        'subtitle': ['1.0625rem', { fontWeight: '500', lineHeight: '1.4' }],
        'body':     ['0.9375rem', { fontWeight: '400', lineHeight: '1.5' }],
        'caption':  ['0.8125rem', { fontWeight: '400', lineHeight: '1.4' }],
        'overline': ['0.6875rem', { fontWeight: '500', letterSpacing: '0.08em' }],
      },
      fontFamily: {
        sans:    ['"DM Sans"', 'system-ui', 'sans-serif'],
        display: ['Syne', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
        ui:      ['"DM Sans"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'nx-xs':   'var(--nx-radius-xs)',
        'nx-sm':   'var(--nx-radius-sm)',
        'nx-md':   'var(--nx-radius-md)',
        'nx-lg':   'var(--nx-radius-lg)',
        'nx-xl':   'var(--nx-radius-xl)',
        'nx-full': 'var(--nx-radius-full)',
        'xl2': '1.125rem',
      },
      spacing: {
        '18': '4.5rem',
      },
      width: {
        'nx-sidebar': 'var(--nx-sidebar-width)',
      },
      transitionDuration: {
        'nx-fast': '150ms',
        'nx-base': '200ms',
        'nx-slow': '350ms',
      },
      boxShadow: {
        'glow-sm':      '0 0 12px -2px var(--color-brand)',
        'glow-md':      '0 0 24px -4px var(--nx-primary-glow)',
        'glass':        'inset 0 1px 0 rgba(255,255,255,0.05)',
        'glow-primary': '0 0 28px var(--nx-primary-glow)',
        'glow-accent':  '0 0 28px var(--nx-accent-glow)',
        'glow-cyan':    '0 0 28px var(--nx-secondary-glow)',
        'glow-hot':     '0 0 28px var(--nx-hot-glow)',
        'glow-violet':  '0 0 18px rgba(124, 111, 250, 0.40)',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, var(--nx-primary) 0%, var(--nx-secondary) 100%)',
        'gradient-accent':  'linear-gradient(135deg, var(--nx-accent) 0%, var(--nx-hot) 100%)',
        'gradient-study':   'linear-gradient(135deg, var(--nx-secondary) 0%, var(--nx-success) 100%)',
        'gradient-fire':    'linear-gradient(135deg, var(--nx-hot) 0%, var(--nx-warning) 100%)',
      },
      keyframes: {
        shimmer: {
          '0%':   { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '1' },
          '50%':       { opacity: '0.55' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%':       { transform: 'translateY(-4px)' },
        },
        'slide-up': {
          '0%':   { transform: 'translateY(8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)',   opacity: '1' },
        },
      },
      animation: {
        'shimmer':    'shimmer 1.5s infinite',
        'pulse-glow': 'pulse-glow 2.5s ease-in-out infinite',
        'float':      'float 3s ease-in-out infinite',
        'slide-up':   'slide-up 200ms ease-out',
      },
    },
  },
  plugins: [],
}
