// src/data/poemas.js
// Adicione novos poemas seguindo este formato.
// language: 'portuguese' | 'english' | 'italian'

export const POEMAS = [
  {
    id: 'borges-remordimiento',
    title: 'El remordimiento',
    author: 'Jorge Luis Borges',
    language: 'spanish', // whisper aceita 'spanish' também
    xpReward: 120,
    threshold: 80,
    lines: [
      'He cometido el peor de los pecados',
      'que un hombre puede cometer. No he sido',
      'feliz. Que los glaciares del olvido',
      'me arrastren y me pierdan, despiadados.',
      'Mis padres me engendraron para el juego',
      'arriesgado y hermoso de la vida,',
      'para la tierra, el agua, el aire, el fuego.',
      'Los defraudé. No fui feliz. Cumplida',
      'no fue su joven voluntad. Mi mente',
      'se aplicó a las simétricas porfías',
      'del arte, que entreteje naderías.',
      'Me legaron valor. No fui valiente.',
      'No me abandona. Siempre está a mi lado',
      'La sombra de haber sido un desdichado.',
    ],
  },
  {
    id: 'drummond-quadrilha',
    title: 'Quadrilha',
    author: 'Carlos Drummond de Andrade',
    language: 'portuguese',
    xpReward: 80,
    threshold: 75,
    lines: [
      'João amava Teresa que amava Raimundo',
      'que amava Maria que amava Joaquim que amava Lili',
      'que não amava ninguém.',
      'João foi para os Estados Unidos, Teresa para o convento,',
      'Raimundo morreu de desastre, Maria ficou para tia,',
      'Joaquim suicidou-se e Lili casou com J. Pinto Fernandes',
      'que não tinha entrado na história.',
    ],
  },
  {
    id: 'drummond-pedra',
    title: 'No meio do caminho',
    author: 'Carlos Drummond de Andrade',
    language: 'portuguese',
    xpReward: 90,
    threshold: 80,
    lines: [
      'No meio do caminho tinha uma pedra',
      'tinha uma pedra no meio do caminho',
      'tinha uma pedra',
      'no meio do caminho tinha uma pedra.',
      'Nunca me esquecerei desse acontecimento',
      'na vida de minhas retinas tão fatigadas.',
      'Nunca me esquecerei que no meio do caminho',
      'tinha uma pedra',
      'tinha uma pedra no meio do caminho',
      'no meio do caminho tinha uma pedra.',
    ],
  },
  {
    id: 'frost-road',
    title: 'The Road Not Taken',
    author: 'Robert Frost',
    language: 'english',
    xpReward: 100,
    threshold: 80,
    lines: [
      'Two roads diverged in a yellow wood,',
      'And sorry I could not travel both',
      'And be one traveler, long I stood',
      'And looked down one as far as I could',
      'To where it bent in the undergrowth;',
      'I shall be telling this with a sigh',
      'Somewhere ages and ages hence:',
      'Two roads diverged in a wood, and I,',
      'I took the one less traveled by,',
      'And that has made all the difference.',
    ],
  },
  {
    id: 'leopardi-infinito',
    title: "L'infinito",
    author: 'Giacomo Leopardi',
    language: 'italian',
    xpReward: 110,
    threshold: 75,
    lines: [
      'Sempre caro mi fu quest\'ermo colle,',
      'e questa siepe, che da tanta parte',
      'dell\'ultimo orizzonte il guardo esclude.',
      'Ma sedendo e mirando, interminati',
      'spazi di là da quella, e sovrumani',
      'silenzi, e profondissima quiete',
      'io nel pensier mi fingo; ove per poco',
      'il cor non si spaura.',
      'E come il vento odo stormir tra queste piante,',
      'io quello infinito silenzio a questa voce',
      'vo comparando: e mi sovvien l\'eterno,',
      'e le morte stagioni, e la presente',
      'e viva, e il suon di lei.',
      'Così tra questa immensità s\'annega il pensier mio:',
      'e il naufragar m\'è dolce in questo mare.',
    ],
  },
]

// Mapa de idiomas para exibição na UI
export const LANGUAGE_LABELS = {
  portuguese: 'Português',
  english: 'English',
  italian: 'Italiano',
  spanish: 'Español',
}
