/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./app/src/**/*.{js,ts,jsx,tsx}"],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-base': 'var(--surface-base)',
        'surface-raised': 'var(--surface-raised)',
        'surface-card': 'var(--surface-card)',
        'surface-elevated': 'var(--surface-elevated)',
        'surface-border': 'var(--surface-border)',
        'bg-primary': 'var(--surface-base)',
        'bg-secondary': 'var(--surface-raised)',
        'bg-tertiary': 'var(--surface-card)',
        'accent-main': 'var(--color-brand)',
        'accent-light': 'var(--color-chat)',
        'text-primary': 'var(--text-hi)',
        'text-secondary': 'var(--text-mid)',
        'text-muted': 'var(--text-lo)',
        'text-hi': 'var(--text-hi)',
        'text-mid': 'var(--text-mid)',
        'text-lo': 'var(--text-lo)',
        'border-subtle': 'var(--surface-border)',
        'color-brand': 'var(--color-brand)',
        'color-notas': 'var(--color-notas)',
        'color-estudo': 'var(--color-estudo)',
        'color-flashcards': 'var(--color-flashcards)',
        'color-gerador': 'var(--color-gerador)',
        'color-chat': 'var(--color-chat)',
        'color-grafo': 'var(--color-grafo)',
        'color-stats': 'var(--color-stats)',
        'color-warning': 'var(--color-warning)',
        'color-success': 'var(--color-success)',
        'color-error': 'var(--color-error)',
        'success': 'var(--color-success)',
        'warning': 'var(--color-warning)',
        'danger': 'var(--color-error)',
        'info': 'var(--color-info)',
        'xp': 'var(--color-gerador)',
      },
      fontFamily: { 
        sans: ['"DM Sans"', 'system-ui', 'sans-serif'], 
        display: ['Syne', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'] 
      },
    },
  },
  plugins: [],
}